stages:
  - build

cache:
  paths:
    - functions/node_modules/

before_script:
  # Install Firebase CLI if it's not already installed
  - npm install -g firebase-tools

build:
  stage: build
  script:
    # Install dependencies
    - npm install
    # Build your project (e.g., for a React app, Vue app, etc.)
    - npm run build
  artifacts:
    paths:
      - public/
    expire_in: 1 day

deploy:
  stage: deploy
  only:
    - main  # Deploys only when the main branch is updated; adjust to your preferred branch
  dependencies:
    - build
  script:
    # Deploy to Firebase using the token from GitLab CI/CD variables
    - firebase deploy --token "$FIREBASE_TOKEN" --only hosting
  environment:
    name: production
    url: https://your-firebase-site.web.app